language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5

install:
  - pip install Django==$DJANGO_VERSION --use-mirrors

script: python runtests.py

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.3.7
    - python: "3.3"
      env: DJANGO_VERSION=1.4.5
    - python: "2.5"
      env: DJANGO_VERSION=1.5
