language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.2.7
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install $DJANGO --use-mirrors

script: python runtests.py

matrix:
  exclude:
    - python: "2.5"
      env: DJANGO=Django==1.5
    - python: "2.5"
      env: DJANGO=https://github.com/django/django/tarball/master
